# Site settings
title: The Autoscores blog
url: "http://blog.autoscores.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  Autoscores is a web application that helps car managers better price their vehicles. Using big data, we can predict when your cars will sell.

# Your information
email: noah@autoscores.com
author: Noah John
avatar: "//www.gravatar.com/avatar/99381c13bdb9229356e9e26174a2854e?d=mm&s=135"
profile: Co-founder/Chief Data Scientist
twitter_username: noahajohn
# github_username:  noahajohn
linkedin_username: noahajohn
instagram_username: noahajohn

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: noahajohn
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
